# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Chaoqun Guo
tagline:          ''
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://chaoqun-guo.github.io
baseurl:          /

author:
  name:           'Chaoqun Guo'
  url:            https://chaoqun-guo.github.io

paginate:         5

# Custom vars
version:          1.0.0


